### ISSUE TITLE
Path to query fasta files

### ISSUE THREAD

**Issue by Yijia-Xiao** [Rostlab/EAT#3]
Hi, thanks for the great work! I tried running the commands in the `Usage` section in README, but the command throws a `FileNotFoundError`.
It seems that there is a minor problem in the path. And I have created a Pull Request [here](https://github.com/Rostlab/EAT/pull/2).

Best,
Yijia Xiao

**Comment by mheinzinger** [comment]
Good spot, thanks! - I've merged your pull request.

**Comment by Yijia-Xiao** [comment]
Happy to help :-)
